# Question 1
What version of NumpPy is installed?

In [1]:
import numpy as np
np.__version__

'1.23.5'

# Question 2
How many records are in the dataset? (specify the number of rows)

**Answer: 11914**

In [4]:
import pandas as pd
df = pd.read_csv('data.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11914 entries, 0 to 11913
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Make               11914 non-null  object 
 1   Model              11914 non-null  object 
 2   Year               11914 non-null  int64  
 3   Engine Fuel Type   11911 non-null  object 
 4   Engine HP          11845 non-null  float64
 5   Engine Cylinders   11884 non-null  float64
 6   Transmission Type  11914 non-null  object 
 7   Driven_Wheels      11914 non-null  object 
 8   Number of Doors    11908 non-null  float64
 9   Market Category    8172 non-null   object 
 10  Vehicle Size       11914 non-null  object 
 11  Vehicle Style      11914 non-null  object 
 12  highway MPG        11914 non-null  int64  
 13  city mpg           11914 non-null  int64  
 14  Popularity         11914 non-null  int64  
 15  MSRP               11914 non-null  int64  
dtypes: float64(3), int64(5

# Question 3
Who are the most frequent car manufactures (top 3) according to the dataset?

**Answer: Chevrolet, Ford, Volkswagen**

In [9]:
df.head()
df['Make'].value_counts()[:3]

Chevrolet     1123
Ford           881
Volkswagen     809
Name: Make, dtype: int64

# Question 4
What's the number of unique Audi car models in the dataset?

In [15]:
df.loc[df['Make'] == 'Audi']['Model'].nunique()

34

# Question 5
How many columns in the dataset have missing values?

In [16]:
count = 0
for col in df.columns:
    if df[col].isnull().sum() > 0:
        count += 1
count

5

# Question 6
1. Find the median value of "Engine Cylinders" column in the dataset.
2. Calculate the most frequent value of the same "Engine Cylinders".
3. Use the `fill na` method to fill the missing values in "Engine Cylinders" with the most frequent value from the previous step.
4. Calculate the median value of "Engine Cylinders" once again.

Has it changed?

**Answer: No**

In [17]:
# part 1
ec_median = df['Engine Cylinders'].median()
print("Engine Cylinder Median:", ec_median)

# part 2
ec_mode = df['Engine Cylinders'].mode()
print("Engine Cylinder Mode:", ec_mode)

# part 3
df['Engine Cylinders'].fillna(ec_mode)

# part 4
print("Engine Cylinder Median:", df['Engine Cylinders'].median())

Engine Cylinder Median: 6.0
Engine Cylinder Mode: 0    4.0
Name: Engine Cylinders, dtype: float64
Engine Cylinder Median: 6.0


# Question 7

1. Select all the "Lotus" cars from the dataset.
2. Select only columns "Engine HP", "Engine Cylinders".
3. Now drop all duplicated rows using `drop_duplicates` method (you should get a dataframe with 9 rows).
4. Get the underlying NumPy array. Let's call it `X`.
5. Compute matrix-matrix multiplication between the transpose of `X` and `X`. To get the transpose, use `X.T`. Let's call the result `XTX`.
6. Compute the inverse of `XTX`.
7. Create an array `y` with values `[1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800]`.
8. Multiply the inverse of `XTX` with the transpose of `X`, and then multiply the result by `y`. Call the result `w`.
9. What's the value of the first element of `w`?

**Answer: 4.59494481**

In [19]:
# part 1
lotus = df.loc[df['Make'] == 'Lotus']

In [21]:
lotus = lotus[['Engine HP', 'Engine Cylinders']]

Engine HP  Engine Cylinders
3912      189.0               4.0
3913      218.0               4.0
3914      189.0               4.0
3915      189.0               4.0
3916      218.0               4.0

In [66]:
lotus = lotus.drop_duplicates()
lotus

Engine HP  Engine Cylinders
3912      189.0               4.0
3913      218.0               4.0
3918      217.0               4.0
4216      350.0               8.0
4257      400.0               6.0
4259      276.0               6.0
4262      345.0               6.0
4292      257.0               4.0
4293      240.0               4.0

In [67]:
X = lotus.values
X

array([[189.,   4.],
       [218.,   4.],
       [217.,   4.],
       [350.,   8.],
       [400.,   6.],
       [276.,   6.],
       [345.,   6.],
       [257.,   4.],
       [240.,   4.]])

In [68]:
XTX = np.matmul(X.T, X)
XTX

array([[7.31684e+05, 1.34100e+04],
       [1.34100e+04, 2.52000e+02]])

In [69]:
inverse_XTX = np.linalg.inv(XTX)

In [70]:
y = [1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800]

In [71]:
w = np.matmul(np.matmul(inverse_XTX, X.T), y)

In [72]:
w

array([  4.59494481, -63.56432501])